@testable import NDKSwiftCore
import XCTest

final class NDKUserTests: XCTestCase {
    // MARK: - Test Properties

    private var ndk: NDK!
    private let testPubkey = "d0a1ffb8761b974cec4a3be8cbcb2e96a7090dcf465ffeac839aa4ca20c9a59e"
    // Note: This npub is generated by the actual Bech32 implementation
    private var testNpub: String {
        (try? Bech32.npub(from: testPubkey)) ?? "npub1invalid"
    }

    override func setUp() async throws {
        try await super.setUp()
        ndk = NDK()
    }

    override func tearDown() async throws {
        ndk = nil
        try await super.tearDown()
    }

    // MARK: - Initialization Tests

    func testInitWithPubkey() {
        let user = NDKUser(pubkey: testPubkey, ndk: ndk)
        XCTAssertEqual(user.pubkey, testPubkey)
        XCTAssertNotNil(user.ndk)
    }

    func testInitWithValidNpub() {
        // Use a known good npub from Bech32Tests
        let knownNpub = "npub180cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsyjh6w6"
        let expectedPubkey = "3bf0c63fcb93463407af97a5e5ee64fa883d107ef9e558472c4eb9aaaefa459d"

        let user = NDKUser(npub: knownNpub, ndk: ndk)
        XCTAssertNotNil(user)
        XCTAssertEqual(user?.pubkey, expectedPubkey)
    }

    func testInitWithInvalidNpub() {
        let user = NDKUser(npub: "invalid_npub", ndk: ndk)
        XCTAssertNil(user)
    }

    func testInitWithEmptyNpub() {
        let user = NDKUser(npub: "", ndk: ndk)
        XCTAssertNil(user)
    }

    func testInitWithWrongPrefixBech32() {
        let user = NDKUser(npub: "nsec1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqsl6a4p", ndk: ndk)
        XCTAssertNil(user)
    }

    // MARK: - Equality and Hashing Tests

    func testEquality() {
        let user1 = NDKUser(pubkey: testPubkey, ndk: ndk)
        let user2 = NDKUser(pubkey: testPubkey, ndk: ndk)
        let user3 = NDKUser(pubkey: "different_pubkey", ndk: ndk)

        XCTAssertEqual(user1, user2)
        XCTAssertNotEqual(user1, user3)
    }

    func testHashable() {
        let user1 = NDKUser(pubkey: testPubkey, ndk: ndk)
        let user2 = NDKUser(pubkey: testPubkey, ndk: ndk)
        let user3 = NDKUser(pubkey: "different_pubkey", ndk: ndk)

        var set = Set<NDKUser>()
        set.insert(user1)
        set.insert(user2)
        set.insert(user3)

        XCTAssertEqual(set.count, 2) // user1 and user2 should be treated as the same
        XCTAssertTrue(set.contains(user1))
        XCTAssertTrue(set.contains(user3))
    }

    // MARK: - Utility Methods Tests

    func testNpubGeneration() {
        let user = NDKUser(pubkey: testPubkey, ndk: ndk)
        let generatedNpub = user.npub

        // Test that it generates a valid npub
        XCTAssertTrue(generatedNpub.hasPrefix("npub1"))
        XCTAssertGreaterThan(generatedNpub.count, 60)

        // Test round-trip conversion
        if let decodedPubkey = try? Bech32.pubkey(from: generatedNpub) {
            XCTAssertEqual(decodedPubkey, testPubkey)
        } else {
            XCTFail("Failed to decode generated npub")
        }
    }

    func testNpubGenerationWithInvalidPubkey() {
        let user = NDKUser(pubkey: "invalid", ndk: ndk)
        // Should return placeholder on encoding failure
        XCTAssertEqual(user.npub, "npub1...")
    }

    func testShortPubkeyWithLongKey() {
        let longPubkey = "d0a1ffb8761b974cec4a3be8cbcb2e96a7090dcf465ffeac839aa4ca20c9a59e"
        let user = NDKUser(pubkey: longPubkey, ndk: ndk)
        let shortened = user.shortPubkey

        XCTAssertTrue(shortened.hasPrefix("d0a1ffb8"))
        XCTAssertTrue(shortened.hasSuffix("0c9a59e"))
        XCTAssertTrue(shortened.contains("..."))
        XCTAssertLessThan(shortened.count, longPubkey.count)
    }

    func testShortPubkeyWithShortKey() {
        let shortPubkey = "d0a1ff"
        let user = NDKUser(pubkey: shortPubkey, ndk: ndk)
        XCTAssertEqual(user.shortPubkey, shortPubkey)
    }

    // MARK: - Relay List Tests

    func testRelayListInitiallyEmpty() {
        let user = NDKUser(pubkey: testPubkey, ndk: ndk)
        XCTAssertEqual(user.relayList, [])
    }

    // MARK: - NIP-46 Tests

    func testNip46UrlsInitiallyNil() {
        let user = NDKUser(pubkey: testPubkey, ndk: ndk)
        XCTAssertNil(user.nip46Urls)
    }

    // MARK: - Following Tests

    func testFollowsReturnsEmptySetWhenNoFollows() async throws {
        let user = NDKUser(pubkey: testPubkey, ndk: ndk)
        let follows = try await user.follows()
        XCTAssertTrue(follows.isEmpty)
    }

    func testFollowsUserReturnsFalseWhenNotFollowing() async throws {
        let user1 = NDKUser(pubkey: testPubkey, ndk: ndk)
        let user2 = NDKUser(pubkey: "3bf0c63fcb93463407af97a5e5ee64fa883d107ef9e558472c4eb9aaaefa459d", ndk: ndk)

        let follows = try await user1.follows(user2)
        XCTAssertFalse(follows)
    }

    // MARK: - Payment Tests

    func testPayThrowsNotImplemented() async throws {
        let user = NDKUser(pubkey: testPubkey, ndk: ndk)

        do {
            _ = try await user.pay(amount: 1000, comment: "Test payment", tags: [["test", "tag"]])
            XCTFail("Should throw not implemented error")
        } catch {
            XCTAssertTrue(error is NDKError)
            if let ndkError = error as? NDKError,
               case let .unknown(message, _) = ndkError
            {
                XCTAssertTrue(message.contains("route payment"))
                XCTAssertTrue(message.contains("Not yet implemented"))
            } else {
                XCTFail("Wrong error type: \(error)")
            }
        }
    }

    // MARK: - GetUser Tests

    func testGetUserWithPubkey() {
        let user = ndk.getUser(testPubkey)
        XCTAssertNotNil(user)
        XCTAssertEqual(user?.pubkey, testPubkey)
    }

    func testGetUserWithNpub() {
        let knownNpub = "npub180cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsyjh6w6"
        let expectedPubkey = "3bf0c63fcb93463407af97a5e5ee64fa883d107ef9e558472c4eb9aaaefa459d"

        let user = ndk.getUser(knownNpub)
        XCTAssertNotNil(user)
        XCTAssertEqual(user?.pubkey, expectedPubkey)
    }

    func testGetUserWithInvalidInput() {
        let user = ndk.getUser("")
        XCTAssertNil(user)
    }

    // MARK: - Sendable Conformance Tests

    func testSendableConformance() {
        let user = NDKUser(pubkey: testPubkey, ndk: ndk)

        // This test verifies that NDKUser can be safely passed between concurrency domains
        Task {
            let capturedUser = user
            XCTAssertEqual(capturedUser.pubkey, testPubkey)
        }
    }
}
