@testable import NDKSwiftCore
import XCTest

final class NDKUserTests: XCTestCase {
    // MARK: - Test Properties

    private let testPubkey = "d0a1ffb8761b974cec4a3be8cbcb2e96a7090dcf465ffeac839aa4ca20c9a59e"
    // Note: This npub is generated by the actual Bech32 implementation
    private var testNpub: String {
        (try? Bech32.npub(from: testPubkey)) ?? "npub1invalid"
    }

    // MARK: - Initialization Tests

    func testInitWithPubkey() {
        let user = NDKUser(pubkey: testPubkey)
        XCTAssertEqual(user.pubkey, testPubkey)
        XCTAssertNil(user.ndk)
    }

    func testInitWithValidNpub() {
        // Use a known good npub from Bech32Tests
        let knownNpub = "npub180cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsyjh6w6"
        let expectedPubkey = "3bf0c63fcb93463407af97a5e5ee64fa883d107ef9e558472c4eb9aaaefa459d"

        let user = NDKUser(npub: knownNpub)
        XCTAssertNotNil(user)
        XCTAssertEqual(user?.pubkey, expectedPubkey)
    }

    func testInitWithInvalidNpub() {
        let user = NDKUser(npub: "invalid_npub")
        XCTAssertNil(user)
    }

    func testInitWithEmptyNpub() {
        let user = NDKUser(npub: "")
        XCTAssertNil(user)
    }

    func testInitWithWrongPrefixBech32() {
        let user = NDKUser(npub: "nsec1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqsl6a4p")
        XCTAssertNil(user)
    }

    // MARK: - Equality and Hashing Tests

    func testEquality() {
        let user1 = NDKUser(pubkey: testPubkey)
        let user2 = NDKUser(pubkey: testPubkey)
        let user3 = NDKUser(pubkey: "different_pubkey")

        XCTAssertEqual(user1, user2)
        XCTAssertNotEqual(user1, user3)
    }

    func testHashable() {
        let user1 = NDKUser(pubkey: testPubkey)
        let user2 = NDKUser(pubkey: testPubkey)
        let user3 = NDKUser(pubkey: "different_pubkey")

        var set = Set<NDKUser>()
        set.insert(user1)
        set.insert(user2)
        set.insert(user3)

        XCTAssertEqual(set.count, 2) // user1 and user2 should be treated as the same
        XCTAssertTrue(set.contains(user1))
        XCTAssertTrue(set.contains(user3))
    }

    // MARK: - Utility Methods Tests

    func testNpubGeneration() {
        let user = NDKUser(pubkey: testPubkey)
        let generatedNpub = user.npub

        // Test that it generates a valid npub
        XCTAssertTrue(generatedNpub.hasPrefix("npub1"))
        XCTAssertGreaterThan(generatedNpub.count, 60)

        // Test round-trip conversion
        if let decodedPubkey = try? Bech32.pubkey(from: generatedNpub) {
            XCTAssertEqual(decodedPubkey, testPubkey)
        } else {
            XCTFail("Failed to decode generated npub")
        }
    }

    func testNpubGenerationWithInvalidPubkey() {
        let user = NDKUser(pubkey: "invalid")
        // Should return placeholder on encoding failure
        XCTAssertEqual(user.npub, "npub1...")
    }

    func testShortPubkeyWithLongKey() {
        let longPubkey = "d0a1ffb8761b974cec4a3be8cbcb2e96a7090dcf465ffeac839aa4ca20c9a59e"
        let user = NDKUser(pubkey: longPubkey)
        let shortened = user.shortPubkey

        XCTAssertTrue(shortened.hasPrefix("d0a1ffb8"))
        XCTAssertTrue(shortened.hasSuffix("0c9a59e"))
        XCTAssertTrue(shortened.contains("..."))
        XCTAssertLessThan(shortened.count, longPubkey.count)
    }

    func testShortPubkeyWithShortKey() {
        let shortPubkey = "d0a1ff"
        let user = NDKUser(pubkey: shortPubkey)
        XCTAssertEqual(user.shortPubkey, shortPubkey)
    }

    // MARK: - Relay List Tests

    func testRelayListAsync() async {
        let user = NDKUser(pubkey: testPubkey)
        let relayList = await user.relayList
        XCTAssertEqual(relayList, [])
    }

    func testFetchRelayListWithoutNDK() async throws {
        let user = NDKUser(pubkey: testPubkey)

        do {
            let _: [NDKRelayInfo] = try await user.fetchRelayList()
            XCTFail("Should throw error when NDK is not set")
        } catch {
            XCTAssertTrue(error is NDKError)
            if let ndkError = error as? NDKError,
               case let .notConfigured(message) = ndkError
            {
                XCTAssertTrue(message.contains("NDK instance not set"))
            } else {
                XCTFail("Wrong error type")
            }
        }
    }

    // MARK: - NIP-46 Tests

    func testNip46UrlsAsync() async {
        let user = NDKUser(pubkey: testPubkey)
        let urls = await user.nip46Urls
        XCTAssertNil(urls)
    }

    // MARK: - Following Tests

    func testFollowsWithoutNDK() async throws {
        let user = NDKUser(pubkey: testPubkey)

        do {
            _ = try await user.follows()
            XCTFail("Should throw error when NDK is not set")
        } catch {
            XCTAssertTrue(error is NDKError)
            if let ndkError = error as? NDKError,
               case let .notConfigured(message) = ndkError
            {
                XCTAssertTrue(message.contains("NDK instance not set"))
            } else {
                XCTFail("Wrong error type")
            }
        }
    }

    func testFollowsUserWithoutNDK() async throws {
        let user1 = NDKUser(pubkey: testPubkey)
        let user2 = NDKUser(pubkey: "other_pubkey")

        do {
            _ = try await user1.follows(user2)
            XCTFail("Should throw error when NDK is not set")
        } catch {
            XCTAssertTrue(error is NDKError)
            if let ndkError = error as? NDKError,
               case let .notConfigured(message) = ndkError
            {
                XCTAssertTrue(message.contains("NDK instance not set"))
            } else {
                XCTFail("Wrong error type")
            }
        }
    }

    // MARK: - NIP-05 Verification Tests

    func testVerifyNIP05WithoutNDK() async throws {
        let user = NDKUser(pubkey: testPubkey)

        do {
            _ = try await user.verifyNIP05()
            XCTFail("Should throw error when NDK is not set")
        } catch {
            XCTAssertTrue(error is NDKError)
            if let ndkError = error as? NDKError,
               case let .notConfigured(message) = ndkError
            {
                XCTAssertTrue(message.contains("NDK instance not set"))
            } else {
                XCTFail("Wrong error type")
            }
        }
    }

    func testVerifyNIP05WithCustomMaxAge() async throws {
        let user = NDKUser(pubkey: testPubkey)
        let customMaxAge: TimeInterval = 3600 // 1 hour

        do {
            _ = try await user.verifyNIP05(maxAge: customMaxAge)
            XCTFail("Should throw error when NDK is not set")
        } catch {
            XCTAssertTrue(error is NDKError)
        }
    }

    // MARK: - Payment Tests

    func testPayWithoutNDK() async throws {
        let user = NDKUser(pubkey: testPubkey)

        do {
            _ = try await user.pay(amount: 1000)
            XCTFail("Should throw error when NDK is not set")
        } catch {
            XCTAssertTrue(error is NDKError)
            if let ndkError = error as? NDKError,
               case let .notConfigured(message) = ndkError
            {
                XCTAssertTrue(message.contains("NDK instance not set"))
            } else {
                XCTFail("Wrong error type")
            }
        }
    }

    func testPayWithNDKNotImplemented() async throws {
        let user = NDKUser(pubkey: testPubkey)
        // Create a minimal NDK instance to pass the nil check
        let ndk = NDK()
        user.ndk = ndk

        do {
            _ = try await user.pay(amount: 1000, comment: "Test payment", tags: [["test", "tag"]])
            XCTFail("Should throw not implemented error")
        } catch {
            XCTAssertTrue(error is NDKError)
            if let ndkError = error as? NDKError,
               case let .unknown(fullMessage, _) = ndkError
            {
                XCTAssertTrue(fullMessage.contains("route payment"))
                XCTAssertTrue(fullMessage.contains("Not yet implemented"))
            } else {
                XCTFail("Wrong error type")
            }
        }
    }

    // MARK: - Thread Safety Tests

    func testConcurrentRelayListAccess() async {
        let user = NDKUser(pubkey: testPubkey)

        // Test concurrent reads
        await withTaskGroup(of: [NDKRelayInfo].self) { group in
            for _ in 0 ..< 100 {
                group.addTask {
                    await user.relayList
                }
            }

            for await result in group {
                XCTAssertEqual(result, [])
            }
        }
    }

    func testConcurrentNip46UrlsAccess() async {
        let user = NDKUser(pubkey: testPubkey)

        // Test concurrent reads
        await withTaskGroup(of: [String]?.self) { group in
            for _ in 0 ..< 100 {
                group.addTask {
                    await user.nip46Urls
                }
            }

            for await result in group {
                XCTAssertNil(result)
            }
        }
    }

    // MARK: - UserStateActor Tests

    func testUserStateActorRelayList() async {
        let actor = UserStateActor()

        // Test initial state
        let initialList = await actor.getRelayList()
        XCTAssertEqual(initialList, [])

        // Test setting relay list
        let relayInfo = NDKRelayInfo(url: "wss://relay.example.com", read: true, write: false)
        await actor.setRelayList([relayInfo])

        let updatedList = await actor.getRelayList()
        XCTAssertEqual(updatedList.count, 1)
        XCTAssertEqual(updatedList.first?.url, "wss://relay.example.com")
        XCTAssertEqual(updatedList.first?.read, true)
        XCTAssertEqual(updatedList.first?.write, false)
    }

    func testUserStateActorNip46Urls() async {
        let actor = UserStateActor()

        // Test initial state
        let initialUrls = await actor.getNip46Urls()
        XCTAssertNil(initialUrls)

        // Test setting URLs
        let urls = ["wss://bunker1.example.com", "wss://bunker2.example.com"]
        await actor.setNip46Urls(urls)

        let updatedUrls = await actor.getNip46Urls()
        XCTAssertEqual(updatedUrls, urls)

        // Test setting to nil
        await actor.setNip46Urls(nil)
        let clearedUrls = await actor.getNip46Urls()
        XCTAssertNil(clearedUrls)
    }

    // MARK: - Sendable Conformance Tests

    func testSendableConformance() {
        let user = NDKUser(pubkey: testPubkey)

        // This test verifies that NDKUser can be safely passed between concurrency domains
        Task {
            let capturedUser = user
            XCTAssertEqual(capturedUser.pubkey, testPubkey)
        }
    }
}
