import Foundation

/// NIP-57 Zap Receipt (kind: 9735)
/// A zap receipt is created by a lightning node when an invoice generated by a zap request is paid.
public struct NDKZapReceipt {
    public let event: NDKEvent
    
    public init(event: NDKEvent) {
        self.event = event
    }
    
    // MARK: - Computed Properties
    
    /// The bolt11 invoice
    public var bolt11: String? {
        get async {
            let tags = await event.tags
            return tags.first(where: { $0.first == "bolt11" })?[safe: 1]
        }
    }
    
    /// The preimage (payment proof)
    public var preimage: String? {
        get async {
            let tags = await event.tags
            return tags.first(where: { $0.first == "preimage" })?[safe: 1]
        }
    }
    
    /// The original zap request as JSON
    public var descriptionJSON: String? {
        get async {
            let tags = await event.tags
            return tags.first(where: { $0.first == "description" })?[safe: 1]
        }
    }
    
    /// The decoded zap request
    public var zapRequest: NDKZapRequest? {
        guard let json = descriptionJSON,
              let data = json.data(using: .utf8),
              let requestEvent = try? JSONDecoder().decode(NDKEvent.self, from: data) else {
            return nil
        }
        return NDKZapRequest(event: requestEvent)
    }
    
    /// Zap recipient's pubkey
    public var recipientPubkey: String? {
        get async {
            let tags = await event.tags
            return tags.first(where: { $0.first == "p" })?[safe: 1]
        }
    }
    
    /// Zap sender's pubkey (optional)
    public var senderPubkey: String? {
        get async {
            let tags = await event.tags
            return tags.first(where: { $0.first == "P" })?[safe: 1]
        }
    }
    
    /// Zapped event ID if this receipt is for an event zap
    public var zappedEventId: String? {
        get async {
            let tags = await event.tags
            return tags.first(where: { $0.first == "e" })?[safe: 1]
        }
    }
    
    /// Zapped event coordinate for addressable events
    public var zappedEventCoordinate: String? {
        get async {
            let tags = await event.tags
            return tags.first(where: { $0.first == "a" })?[safe: 1]
        }
    }
    
    /// Amount in millisatoshis (parsed from bolt11)
    public var amountMillisats: Int64? {
        guard let bolt11 = bolt11 else { return nil }
        return parseBolt11Amount(bolt11)
    }
    
    /// Amount in satoshis
    public var amountSats: Int64? {
        amountMillisats.map { $0 / 1000 }
    }
    
    /// The comment from the original zap request
    public var comment: String? {
        zapRequest?.comment
    }
    
    // MARK: - Validation
    
    /// Validate the zap receipt according to NIP-57 requirements
    /// - Parameters:
    ///   - lnurlProviderPubkey: The pubkey from the recipient's LNURL provider
    ///   - zapRequest: The original zap request to validate against
    /// - Returns: true if valid, false otherwise
    public func validate(lnurlProviderPubkey: String, zapRequest: NDKZapRequest? = nil) async -> Bool {
        // 1. The zap receipt event's pubkey MUST match the provider's nostrPubkey
        let eventPubkey = await event.pubkey
        guard eventPubkey == lnurlProviderPubkey else {
            return false
        }
        
        // 2. If we have the original zap request, validate amounts match
        if let request = zapRequest ?? self.zapRequest,
           let requestAmount = request.amountMillisats,
           let receiptAmount = amountMillisats {
            guard requestAmount == receiptAmount else {
                return false
            }
        }
        
        // 3. Must have required tags
        guard bolt11 != nil,
              descriptionJSON != nil,
              recipientPubkey != nil else {
            return false
        }
        
        // 4. The description should be a valid zap request
        guard self.zapRequest != nil else {
            return false
        }
        
        return true
    }
    
    /// Create a zap receipt from components (for testing or wallet implementations)
    public static func create(
        ndk: NDK,
        signer: NDKSigner,
        zapRequest: NDKZapRequest,
        bolt11: String,
        preimage: String? = nil,
        paidAt: Date = Date()
    ) async throws -> NDKZapReceipt {
        let event = NDKEvent(
            pubkey: "", // Will be set by signer
            createdAt: Timestamp(paidAt.timeIntervalSince1970),
            kind: EventKind.zap,
            content: ""
        )
        
        var tags: [[String]] = []
        
        // Copy p, e, a, P tags from zap request
        for tag in zapRequest.event.tags {
            if let tagName = tag.first,
               ["p", "e", "a", "P"].contains(tagName) {
                tags.append(tag)
            }
        }
        
        // Add bolt11 tag
        tags.append(["bolt11", bolt11])
        
        // Add description tag (JSON-encoded zap request)
        let description = try zapRequest.encodeForCallback()
        tags.append(["description", description])
        
        // Add preimage if available
        if let preimage = preimage {
            tags.append(["preimage", preimage])
        }
        
        for tag in tags {
            event.addTag(tag)
        }
        
        // Sign with the lightning provider's key
        event.pubkey = try await signer.pubkey
        event.sig = try await signer.sign(event)
        
        return NDKZapReceipt(event: event)
    }
}

// MARK: - Bolt11 Parsing

private func parseBolt11Amount(_ bolt11: String) -> Int64? {
    // This is a simplified parser - a full implementation would decode the bolt11 invoice
    // For now, we'll look for the amount in the human-readable part
    
    // Remove "lnbc" prefix and look for amount
    let prefixPattern = #"^lnbc(\d+)([munp]?)"#
    
    guard let regex = try? NSRegularExpression(pattern: prefixPattern, options: .caseInsensitive),
          let match = regex.firstMatch(in: bolt11, options: [], range: NSRange(location: 0, length: bolt11.count)),
          match.numberOfRanges >= 2 else {
        return nil
    }
    
    let amountRange = match.range(at: 1)
    guard let range = Range(amountRange, in: bolt11),
          let amount = Int64(bolt11[range]) else {
        return nil
    }
    
    // Parse multiplier if present
    if match.numberOfRanges >= 3 {
        let multiplierRange = match.range(at: 2)
        if let range = Range(multiplierRange, in: bolt11) {
            let multiplier = String(bolt11[range])
            switch multiplier {
            case "m": return amount // millisats
            case "u": return amount * 1000 // microsats to millisats
            case "n": return amount * 1_000_000 // nanosats to millisats
            case "p": return amount * 1_000_000_000 // picosats to millisats
            default: return amount * 100_000_000_000 // BTC to millisats
            }
        }
    }
    
    // Default: amount is in BTC
    return amount * 100_000_000_000
}
