#!/usr/bin/env swift

// Demonstrates that custom subscription IDs are now preserved exactly as provided
// Run with: swift Examples/DemoCustomSubscriptionId.swift

import Foundation
import NDKSwift

print("🔍 Custom Subscription ID Preservation Demo\n")

// Example 1: NIP-60 Wallet using custom IDs
print("Example 1: NIP-60 Wallet Subscriptions")
print("--------------------------------------")

let walletSubscriptions = [
    ("nip60-quotes", NDKFilter(kinds: [7375])),
    ("nip60-tokens", NDKFilter(kinds: [7376])),
    ("nip60-nutzaps", NDKFilter(kinds: [9321])),
    ("nip60-wallet-events", NDKFilter(kinds: [EventKind.cashuToken, EventKind.nutzap]))
]

for (customId, filter) in walletSubscriptions {
    print("Creating subscription with ID: '\(customId)'")
    print("  Filter: kinds=\(filter.kinds ?? [])")
    print("  ✅ This ID will be sent exactly as '\(customId)' in REQ messages")
    print()
}

// Example 2: Auto-generated IDs
print("\nExample 2: Auto-generated Subscription IDs")
print("------------------------------------------")

let autoGeneratedExamples = [
    NDKFilter(kinds: [1]),           // Will generate: "kind1_<4-chars>"
    NDKFilter(kinds: [0, 3]),        // Will generate: "metadata_follows_<4-chars>"
    NDKFilter(authors: ["pubkey1"])  // Will generate: "author_pubkey1_<4-chars>"
]

for filter in autoGeneratedExamples {
    print("Filter without custom ID:")
    if let kinds = filter.kinds {
        print("  Kinds: \(kinds)")
    }
    if let authors = filter.authors {
        print("  Authors: \(authors)")
    }
    print("  🤖 Will auto-generate ID with format: <description>_<4-char-suffix>")
    print()
}

// Example 3: Outbox model with relay suffixes
print("\nExample 3: Outbox Model (Relay-specific IDs)")
print("--------------------------------------------")

print("Custom ID: 'my-events'")
print("When using outbox model with multiple relays:")
print("  - relay.damus.io → 'my-events_relay.damus.io'")
print("  - nos.lol → 'my-events_nos.lol'")
print("  - relay.nostr.band → 'my-events_relay.nostr.band'")
print("\n✅ Base custom ID preserved, relay suffix added for routing")

print("\n📝 Summary")
print("----------")
print("• Custom subscription IDs are preserved exactly as provided")
print("• No random suffixes are added to custom IDs")
print("• Auto-generated IDs include descriptive prefix + 4-char suffix")
print("• Outbox queries add relay suffix to enable proper routing")
print("\n✨ This change ensures NIP-60 wallets and other apps can rely on stable subscription IDs!")