import Foundation

/// NIP-57 Zap Receipt (kind: 9735)
/// A zap receipt is created by a lightning node when an invoice generated by a zap request is paid.
public struct NDKZapReceipt {
    public let event: NDKEvent

    public init(event: NDKEvent) {
        self.event = event
    }

    // MARK: - Computed Properties

    /// The bolt11 invoice
    public var bolt11: String? {
        return event.tags.first(where: { $0.first == NostrConstants.TagName.bolt11 })?[safe: 1]
    }

    /// The preimage (payment proof)
    public var preimage: String? {
        return event.tags.first(where: { $0.first == NostrConstants.TagName.preimage })?[safe: 1]
    }

    /// The original zap request as JSON
    public var descriptionJSON: String? {
        return event.tags.first(where: { $0.first == NostrConstants.TagName.description })?[safe: 1]
    }

    /// The decoded zap request
    public var zapRequest: NDKZapRequest? {
        guard let json = descriptionJSON,
              let data = json.data(using: .utf8),
              let requestEvent = JSONCoding.safeDecode(NDKEvent.self, from: data)
        else {
            return nil
        }
        return NDKZapRequest(event: requestEvent)
    }

    /// The zap request ID (from the decoded request)
    public var zapRequestId: String? {
        return zapRequest?.event.id
    }

    /// Zap recipient's pubkey
    public var recipientPubkey: String? {
        return event.tags.first(where: { $0.first == "p" })?[safe: 1]
    }

    /// Zap sender's pubkey (optional)
    public var senderPubkey: String? {
        return event.tags.first(where: { $0.first == "P" })?[safe: 1]
    }

    /// Zapped event ID if this receipt is for an event zap
    public var zappedEventId: String? {
        return event.tags.first(where: { $0.first == "e" })?[safe: 1]
    }

    /// Zapped event coordinate for addressable events
    public var zappedEventCoordinate: String? {
        return event.tags.first(where: { $0.first == "a" })?[safe: 1]
    }

    /// Amount in millisatoshis (parsed from bolt11)
    public var amountMillisats: Int64? {
        guard let bolt11 = bolt11 else { return nil }
        return parseBolt11Amount(bolt11)
    }

    /// Amount in satoshis
    public var amountSats: Int64? {
        return amountMillisats.map { PaymentConstants.millisatsToSats($0) }
    }

    /// The comment from the original zap request
    public var comment: String? {
        return zapRequest?.comment
    }

    // MARK: - Validation

    /// Validate the zap receipt according to NIP-57 requirements
    /// - Parameters:
    ///   - lnurlProviderPubkey: The pubkey from the recipient's LNURL provider
    ///   - zapRequest: The original zap request to validate against
    /// - Returns: true if valid, false otherwise
    public func validate(lnurlProviderPubkey: String, zapRequest: NDKZapRequest? = nil) -> Bool {
        // 1. The zap receipt event's pubkey MUST match the provider's nostrPubkey
        let eventPubkey = event.pubkey
        guard eventPubkey == lnurlProviderPubkey else {
            return false
        }

        // 2. If we have the original zap request, validate amounts match
        let effectiveRequest = zapRequest ?? self.zapRequest
        if let request = effectiveRequest,
           let requestAmount = request.amountMillisats,
           let receiptAmount = amountMillisats {
            guard requestAmount == receiptAmount else {
                return false
            }
        }

        // 3. Must have required tags
        guard bolt11 != nil,
              descriptionJSON != nil,
              recipientPubkey != nil
        else {
            return false
        }

        // 4. The description should be a valid zap request
        guard self.zapRequest != nil else {
            return false
        }

        return true
    }

    /// Create a zap receipt from components (for testing or wallet implementations)
    public static func create(
        ndk: NDK,
        signer: NDKSigner,
        zapRequest: NDKZapRequest,
        bolt11: String,
        preimage: String? = nil,
        paidAt: Date = Date()
    ) async throws -> NDKZapReceipt {
        var tags: [[String]] = []

        // Copy p, e, a, P tags from zap request
        for tag in zapRequest.event.tags {
            if let tagName = tag.first,
               [NostrConstants.TagName.pubkey,
                NostrConstants.TagName.event,
                NostrConstants.TagName.address,
                NostrConstants.TagName.uppercasePubkey].contains(tagName) {
                tags.append(tag)
            }
        }

        // Add bolt11 tag
        tags.append([NostrConstants.TagName.bolt11, bolt11])

        // Add description tag (JSON-encoded zap request)
        let description = try zapRequest.encodeForCallback()
        tags.append([NostrConstants.TagName.description, description])

        // Add preimage if available
        if let preimage = preimage {
            tags.append([NostrConstants.TagName.preimage, preimage])
        }

        let event = try await NDKEventBuilder(ndk: ndk)
            .content("")
            .kind(EventKind.zap)
            .tags(tags)
            .createdAt(paidAt.nostrTimestamp)
            .build(signer: signer)

        return NDKZapReceipt(event: event)
    }
}

// MARK: - Bolt11 Parsing

private func parseBolt11Amount(_ bolt11: String) -> Int64? {
    // Use comprehensive Bolt11 parser
    guard let invoice = Bolt11Parser.decode(string: bolt11),
          let amount = invoice.amount
    else {
        return nil
    }

    // Convert satoshis to millisatoshis
    return amount.int64
}
